server:
  port: 8888


spring:
#  data:
#    elasticsearch:
#      cluster-nodes: localhost:9300
#      cluster-name: elasticsearchdemo
#      repositories:
#        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/1902?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/fm/
  redis:
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
        max-wait: -1
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
          max-interval: 6000
          multiplier: 20
      simple:
        default-requeue-rejected: true
  elasticsearch:
    rest:
      uris: http://localhost:9200/


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.mr.model_demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl